  name: meetdigest
  description: "A new Flutter project."
  publish_to: 'none'
  version: 1.0.0+1

  environment:
    sdk: ^3.7.2

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.8
    flutter_svg: ^2.1.0
    flutter_sound: ^9.2.13
    path_provider: ^2.1.1
    permission_handler: ^11.3.0
    external_path: ^2.2.0
    file_selector: ^1.0.3
    cross_file: ^0.3.3
    record: ^6.0.0
    shared_preferences: ^2.2.2
    dotted_border: ^2.0.0
    http: ^1.2.1


  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^5.0.0

  flutter:
    uses-material-design: true

    assets:
      - assets/images/
      - assets/svgs/